name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install composer init
      run: composer require
      
    - name: install composer
      run: composer install 
      
    - name: install phpunit
      run: composer require --dev phpunit/phpunit  
      
    - name: update composer
      run: composer update

      
    - name: install csfixer
      run: composer global require friendsofphp/php-cs-fixer
      
    - name: install phpstan
      run: composer require --dev phpstan/phpstan
      
    - name: test uni
      run: composer exec phpunit tests/unitTests/ContactServiceUnitTest.php
      
    - name: test inte
      run: composer exec phpunit tests/integrationTests/ContactServiceIntegrationTest.php
      
 
      
 
      
 
     
